# Base image
FROM node:18-alpine

# Set app directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --production

# Copy the rest of the project
COPY . .

# Expose App Runner port
EXPOSE 8080

# Start the API
CMD ["node", "server.js"]
